site_name: react-json-schema-form-builder documentation
docs_dir: docs
theme: readthedocs

extra_javascript: []

nav:
  - Home: index.md
  - Installation: Installation.md
  - Background: Background.md
  - Usage: Usage.md
  - Mods: Mods.md
  - Contributing: https://github.com/ginkgobioworks/react-json-schema-form-builder/blob/main/CONTRIBUTING.md
  - Bugs: https://github.com/ginkgobioworks/react-json-schema-form-builder/issues
  - Repository: https://github.com/ginkgobioworks/react-json-schema-form-builder

markdown_extensions:
  - toc:
      permalink: true
